name: water_taxi_miami
description: Water Taxi Miami

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  overlay_support: ^1.0.5
  cloud_firestore: ^0.14.3
  firebase_core: ^0.5.2
  uuid: ^2.2.2
  intl: ^0.16.1
  share: ^0.6.5+4
  logger: ^0.9.2
  shared_preferences: ^0.5.12+4
  firebase_messaging: ^7.0.3
  pin_input_text_field: ^3.3.0
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
